using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FaunaFinder.Aspire.Generators;

[Generator]
public class DeployableResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all AddProject invocations
        var addProjectCalls = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsAddProjectInvocation(node),
                transform: static (ctx, _) => GetResourceMapping(ctx))
            .Where(static m => m is not null);

        // Combine all mappings and generate the source
        var collected = addProjectCalls.Collect();

        context.RegisterSourceOutput(collected, static (spc, mappings) =>
        {
            var source = GenerateSource(mappings!);
            spc.AddSource("DeployableResources.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static bool IsAddProjectInvocation(SyntaxNode node)
    {
        // Look for method invocations like builder.AddProject<T>("name")
        if (node is not InvocationExpressionSyntax invocation)
            return false;

        if (invocation.Expression is not MemberAccessExpressionSyntax memberAccess)
            return false;

        if (memberAccess.Name is not GenericNameSyntax genericName)
            return false;

        return genericName.Identifier.Text == "AddProject";
    }

    private static ResourceMapping? GetResourceMapping(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var memberAccess = (MemberAccessExpressionSyntax)invocation.Expression;
        var genericName = (GenericNameSyntax)memberAccess.Name;

        // Get the generic type argument (e.g., Projects.FaunaFinder_Server)
        var typeArg = genericName.TypeArgumentList.Arguments.FirstOrDefault();
        if (typeArg is null)
            return null;

        // Get the project name from the type
        var projectTypeName = typeArg.ToString();

        // Convert Projects.FaunaFinder_Server to FaunaFinder.Server
        var projectName = projectTypeName
            .Replace("Projects.", "")
            .Replace("_", ".");

        // Get the resource name from the first argument (the string literal)
        var args = invocation.ArgumentList.Arguments;
        if (args.Count == 0)
            return null;

        var firstArg = args[0].Expression;
        if (firstArg is not LiteralExpressionSyntax literal)
            return null;

        if (!literal.IsKind(SyntaxKind.StringLiteralExpression))
            return null;

        var resourceName = literal.Token.ValueText;

        return new ResourceMapping(resourceName, projectName);
    }

    private static string GenerateSource(ImmutableArray<ResourceMapping?> mappings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace FaunaFinder.Aspire.Generators;");
        sb.AppendLine();
        sb.AppendLine("public static class DeployableResources");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps Aspire resource names to their project names.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyDictionary<string, string> ResourceToProject { get; } = new Dictionary<string, string>");
        sb.AppendLine("    {");

        foreach (var mapping in mappings)
        {
            if (mapping is not null)
            {
                sb.AppendLine($"        [\"{mapping.ResourceName}\"] = \"{mapping.ProjectName}\",");
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps project names to their Aspire resource names.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyDictionary<string, string> ProjectToResource { get; } = new Dictionary<string, string>");
        sb.AppendLine("    {");

        foreach (var mapping in mappings)
        {
            if (mapping is not null)
            {
                sb.AppendLine($"        [\"{mapping.ProjectName}\"] = \"{mapping.ResourceName}\",");
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the list of all deployable resource names.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyList<string> AllResources { get; } = new[]");
        sb.AppendLine("    {");

        foreach (var mapping in mappings)
        {
            if (mapping is not null)
            {
                sb.AppendLine($"        \"{mapping.ResourceName}\",");
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private class ResourceMapping
    {
        public string ResourceName { get; }
        public string ProjectName { get; }

        public ResourceMapping(string resourceName, string projectName)
        {
            ResourceName = resourceName;
            ProjectName = projectName;
        }
    }
}
