// <auto-generated />
using System;
using FaunaFinder.Wildlife.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaunaFinder.Wildlife.Database.Migrations
{
    [DbContext(typeof(WildlifeDbContext))]
    [Migration("20260129001450_InitialWildlife")]
    partial class InitialWildlife
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audio_content_type");

                    b.Property<byte[]>("AudioData")
                        .HasColumnType("bytea")
                        .HasColumnName("audio_data");

                    b.Property<int>("Behaviors")
                        .HasColumnType("integer")
                        .HasColumnName("behaviors");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confidence");

                    b.Property<string>("Count")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Evidence")
                        .HasColumnType("integer")
                        .HasColumnName("evidence");

                    b.Property<bool>("IsFlaggedForReview")
                        .HasColumnType("boolean")
                        .HasColumnName("is_flagged_for_review");

                    b.Property<bool>("IsNewMunicipalityRecord")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_municipality_record");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("integer")
                        .HasColumnName("municipality_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("photo_content_type");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("bytea")
                        .HasColumnName("photo_data");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_notes");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UserSpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("user_species_id");

                    b.Property<string>("Weather")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("weather");

                    b.HasKey("Id")
                        .HasName("pk_sightings");

                    b.HasIndex("IsFlaggedForReview")
                        .HasDatabaseName("sightings_is_flagged_for_review_idx");

                    b.HasIndex("Location")
                        .HasDatabaseName("sightings_location_gist_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("sightings_observed_at_idx");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("sightings_reported_by_user_id_idx");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_sightings_species_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("sightings_status_idx");

                    b.HasIndex("UserSpeciesId")
                        .HasDatabaseName("ix_sightings_user_species_id");

                    b.ToTable("sightings", null, t =>
                        {
                            t.HasCheckConstraint("CK_sightings_species_reference", "species_id IS NOT NULL OR user_species_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profile_image_content_type");

                    b.Property<byte[]>("ProfileImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("profile_image_data");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("ScientificName")
                        .IsUnique()
                        .HasDatabaseName("species_scientific_name_uidx");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.SpeciesLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_meters");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_species_locations");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("species_locations_species_id_idx");

                    b.ToTable("species_locations", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.UserSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedSpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_species_id");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEndangered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_endangered");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("photo_content_type");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("bytea")
                        .HasColumnName("photo_data");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_species");

                    b.HasIndex("ApprovedSpeciesId")
                        .HasDatabaseName("ix_user_species_approved_species_id");

                    b.HasIndex("CommonName")
                        .HasDatabaseName("user_species_common_name_idx");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("user_species_is_verified_idx");

                    b.ToTable("user_species", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.Sighting", b =>
                {
                    b.HasOne("FaunaFinder.Wildlife.Database.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sightings_species_species_id");

                    b.HasOne("FaunaFinder.Wildlife.Database.Models.UserSpecies", "UserSpecies")
                        .WithMany("Sightings")
                        .HasForeignKey("UserSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sightings_user_species_user_species_id");

                    b.Navigation("Species");

                    b.Navigation("UserSpecies");
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.Species", b =>
                {
                    b.OwnsMany("FaunaFinder.i18n.Contracts.LocaleValue", "CommonName", b1 =>
                        {
                            b1.Property<int>("SpeciesId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("SpeciesId", "__synthesizedOrdinal");

                            b1.ToTable("species");

                            b1.ToJson("common_name");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesId")
                                .HasConstraintName("fk_species_species_species_id");
                        });

                    b.Navigation("CommonName");
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.SpeciesLocation", b =>
                {
                    b.HasOne("FaunaFinder.Wildlife.Database.Models.Species", "Species")
                        .WithMany("Locations")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_locations_species_species_id");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.UserSpecies", b =>
                {
                    b.HasOne("FaunaFinder.Wildlife.Database.Models.Species", "ApprovedSpecies")
                        .WithMany()
                        .HasForeignKey("ApprovedSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_species_species_approved_species_id");

                    b.Navigation("ApprovedSpecies");
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.Species", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("FaunaFinder.Wildlife.Database.Models.UserSpecies", b =>
                {
                    b.Navigation("Sightings");
                });
#pragma warning restore 612, 618
        }
    }
}
