// <auto-generated />
using FaunaFinder.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaunaFinder.Database.Migrations
{
    [DbContext(typeof(FaunaFinderContext))]
    [Migration("20260126011318_SimplifyToSingleProfileImage")]
    partial class SimplifyToSingleProfileImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.FwsAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fws_actions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("fws_actions_code_uidx");

                    b.ToTable("fws_actions", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.FwsLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FwsActionId")
                        .HasColumnType("integer")
                        .HasColumnName("fws_action_id");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("justification");

                    b.Property<int>("NrcsPracticeId")
                        .HasColumnType("integer")
                        .HasColumnName("nrcs_practice_id");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_fws_links");

                    b.HasIndex("FwsActionId")
                        .HasDatabaseName("ix_fws_links_fws_action_id");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_fws_links_species_id");

                    b.HasIndex("NrcsPracticeId", "FwsActionId", "SpeciesId")
                        .HasDatabaseName("fws_links_practice_action_species_idx");

                    b.ToTable("fws_links", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.NrcsPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_nrcs_practices");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("nrcs_practices_code_uidx");

                    b.ToTable("nrcs_practices", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Municipalities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry(Geometry, 4326)")
                        .HasColumnName("boundary");

                    b.Property<string>("GeoJsonId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("geo_json_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_municipalities");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("municipalities_boundary_gist_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("GeoJsonId")
                        .IsUnique()
                        .HasDatabaseName("municipalities_geojson_id_uidx");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("municipalities_name_uidx");

                    b.ToTable("municipalities", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Municipalities.MunicipalitySpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("integer")
                        .HasColumnName("municipality_id");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_municipality_species");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_municipality_species_species_id");

                    b.HasIndex("MunicipalityId", "SpeciesId")
                        .IsUnique()
                        .HasDatabaseName("municipality_species_municipality_species_uidx");

                    b.ToTable("municipality_species", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profile_image_content_type");

                    b.Property<byte[]>("ProfileImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("profile_image_data");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("ScientificName")
                        .IsUnique()
                        .HasDatabaseName("species_scientific_name_uidx");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.SpeciesLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_meters");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_species_locations");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("species_locations_species_id_idx");

                    b.ToTable("species_locations", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.FwsLink", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Conservation.FwsAction", "FwsAction")
                        .WithMany("FwsLinks")
                        .HasForeignKey("FwsActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_fws_actions_fws_action_id");

                    b.HasOne("FaunaFinder.Database.Models.Conservation.NrcsPractice", "NrcsPractice")
                        .WithMany("FwsLinks")
                        .HasForeignKey("NrcsPracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_nrcs_practices_nrcs_practice_id");

                    b.HasOne("FaunaFinder.Database.Models.Species.Species", "Species")
                        .WithMany("FwsLinks")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_species_species_id");

                    b.Navigation("FwsAction");

                    b.Navigation("NrcsPractice");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Municipalities.MunicipalitySpecies", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Municipalities.Municipality", "Municipality")
                        .WithMany("MunicipalitySpecies")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipality_species_municipalities_municipality_id");

                    b.HasOne("FaunaFinder.Database.Models.Species.Species", "Species")
                        .WithMany("MunicipalitySpecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipality_species_species_species_id");

                    b.Navigation("Municipality");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.Species", b =>
                {
                    b.OwnsMany("FaunaFinder.Contracts.Localization.LocaleValue", "CommonName", b1 =>
                        {
                            b1.Property<int>("SpeciesId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("SpeciesId", "__synthesizedOrdinal");

                            b1.ToTable("species");

                            b1.ToJson("common_name");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesId")
                                .HasConstraintName("fk_species_species_species_id");
                        });

                    b.Navigation("CommonName");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.SpeciesLocation", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Species.Species", "Species")
                        .WithMany("Locations")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_locations_species_species_id");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.FwsAction", b =>
                {
                    b.Navigation("FwsLinks");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.NrcsPractice", b =>
                {
                    b.Navigation("FwsLinks");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Municipalities.Municipality", b =>
                {
                    b.Navigation("MunicipalitySpecies");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.Species", b =>
                {
                    b.Navigation("FwsLinks");

                    b.Navigation("Locations");

                    b.Navigation("MunicipalitySpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
