// <auto-generated />
using System;
using FaunaFinder.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaunaFinder.Database.Migrations
{
    [DbContext(typeof(FaunaFinderContext))]
    [Migration("20260127015033_AddWildlifeDiscoveryTables")]
    partial class AddWildlifeDiscoveryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.FwsAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fws_actions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("fws_actions_code_uidx");

                    b.ToTable("fws_actions", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.FwsLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FwsActionId")
                        .HasColumnType("integer")
                        .HasColumnName("fws_action_id");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("justification");

                    b.Property<int>("NrcsPracticeId")
                        .HasColumnType("integer")
                        .HasColumnName("nrcs_practice_id");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_fws_links");

                    b.HasIndex("FwsActionId")
                        .HasDatabaseName("ix_fws_links_fws_action_id");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_fws_links_species_id");

                    b.HasIndex("NrcsPracticeId", "FwsActionId", "SpeciesId")
                        .HasDatabaseName("fws_links_practice_action_species_idx");

                    b.ToTable("fws_links", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.NrcsPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_nrcs_practices");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("nrcs_practices_code_uidx");

                    b.ToTable("nrcs_practices", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Municipalities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry(Geometry, 4326)")
                        .HasColumnName("boundary");

                    b.Property<string>("GeoJsonId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("geo_json_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_municipalities");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("municipalities_boundary_gist_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("GeoJsonId")
                        .IsUnique()
                        .HasDatabaseName("municipalities_geojson_id_uidx");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("municipalities_name_uidx");

                    b.ToTable("municipalities", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Municipalities.MunicipalitySpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("integer")
                        .HasColumnName("municipality_id");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_municipality_species");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_municipality_species_species_id");

                    b.HasIndex("MunicipalityId", "SpeciesId")
                        .IsUnique()
                        .HasDatabaseName("municipality_species_municipality_species_uidx");

                    b.ToTable("municipality_species", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Sightings.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audio_content_type");

                    b.Property<byte[]>("AudioData")
                        .HasColumnType("bytea")
                        .HasColumnName("audio_data");

                    b.Property<int>("Behaviors")
                        .HasColumnType("integer")
                        .HasColumnName("behaviors");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confidence");

                    b.Property<string>("Count")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Evidence")
                        .HasColumnType("integer")
                        .HasColumnName("evidence");

                    b.Property<bool>("IsFlaggedForReview")
                        .HasColumnType("boolean")
                        .HasColumnName("is_flagged_for_review");

                    b.Property<bool>("IsNewMunicipalityRecord")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_municipality_record");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("integer")
                        .HasColumnName("municipality_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("photo_content_type");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("bytea")
                        .HasColumnName("photo_data");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_notes");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UserSpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("user_species_id");

                    b.Property<string>("Weather")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("weather");

                    b.HasKey("Id")
                        .HasName("pk_sightings");

                    b.HasIndex("IsFlaggedForReview")
                        .HasDatabaseName("sightings_is_flagged_for_review_idx");

                    b.HasIndex("Location")
                        .HasDatabaseName("sightings_location_gist_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("ix_sightings_municipality_id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("sightings_observed_at_idx");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("sightings_reported_by_user_id_idx");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_sightings_reviewed_by_user_id");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_sightings_species_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("sightings_status_idx");

                    b.HasIndex("UserSpeciesId")
                        .HasDatabaseName("ix_sightings_user_species_id");

                    b.ToTable("sightings", null, t =>
                        {
                            t.HasCheckConstraint("CK_sightings_species_reference", "species_id IS NOT NULL OR user_species_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Sightings.UserSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedSpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_species_id");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEndangered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_endangered");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("photo_content_type");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("bytea")
                        .HasColumnName("photo_data");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_species");

                    b.HasIndex("ApprovedSpeciesId")
                        .HasDatabaseName("ix_user_species_approved_species_id");

                    b.HasIndex("CommonName")
                        .HasDatabaseName("user_species_common_name_idx");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_user_species_created_by_user_id");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("user_species_is_verified_idx");

                    b.HasIndex("VerifiedByUserId")
                        .HasDatabaseName("ix_user_species_verified_by_user_id");

                    b.ToTable("user_species", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profile_image_content_type");

                    b.Property<byte[]>("ProfileImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("profile_image_data");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("ScientificName")
                        .IsUnique()
                        .HasDatabaseName("species_scientific_name_uidx");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.SpeciesLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_meters");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_species_locations");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("species_locations_species_id_idx");

                    b.ToTable("species_locations", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.FwsLink", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Conservation.FwsAction", "FwsAction")
                        .WithMany("FwsLinks")
                        .HasForeignKey("FwsActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_fws_actions_fws_action_id");

                    b.HasOne("FaunaFinder.Database.Models.Conservation.NrcsPractice", "NrcsPractice")
                        .WithMany("FwsLinks")
                        .HasForeignKey("NrcsPracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_nrcs_practices_nrcs_practice_id");

                    b.HasOne("FaunaFinder.Database.Models.Species.Species", "Species")
                        .WithMany("FwsLinks")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_species_species_id");

                    b.Navigation("FwsAction");

                    b.Navigation("NrcsPractice");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Municipalities.MunicipalitySpecies", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Municipalities.Municipality", "Municipality")
                        .WithMany("MunicipalitySpecies")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipality_species_municipalities_municipality_id");

                    b.HasOne("FaunaFinder.Database.Models.Species.Species", "Species")
                        .WithMany("MunicipalitySpecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipality_species_species_species_id");

                    b.Navigation("Municipality");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Sightings.Sighting", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Municipalities.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sightings_municipalities_municipality_id");

                    b.HasOne("FaunaFinder.Database.Models.Users.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sightings_users_reported_by_user_id");

                    b.HasOne("FaunaFinder.Database.Models.Users.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sightings_users_reviewed_by_user_id");

                    b.HasOne("FaunaFinder.Database.Models.Species.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sightings_species_species_id");

                    b.HasOne("FaunaFinder.Database.Models.Sightings.UserSpecies", "UserSpecies")
                        .WithMany("Sightings")
                        .HasForeignKey("UserSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sightings_user_species_user_species_id");

                    b.Navigation("Municipality");

                    b.Navigation("ReportedByUser");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Species");

                    b.Navigation("UserSpecies");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Sightings.UserSpecies", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Species.Species", "ApprovedSpecies")
                        .WithMany()
                        .HasForeignKey("ApprovedSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_species_species_approved_species_id");

                    b.HasOne("FaunaFinder.Database.Models.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_species_users_created_by_user_id");

                    b.HasOne("FaunaFinder.Database.Models.Users.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_species_users_verified_by_user_id");

                    b.Navigation("ApprovedSpecies");

                    b.Navigation("CreatedByUser");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.Species", b =>
                {
                    b.OwnsMany("FaunaFinder.Contracts.Localization.LocaleValue", "CommonName", b1 =>
                        {
                            b1.Property<int>("SpeciesId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("SpeciesId", "__synthesizedOrdinal");

                            b1.ToTable("species");

                            b1.ToJson("common_name");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesId")
                                .HasConstraintName("fk_species_species_species_id");
                        });

                    b.Navigation("CommonName");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.SpeciesLocation", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Species.Species", "Species")
                        .WithMany("Locations")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_locations_species_species_id");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("FaunaFinder.Database.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FaunaFinder.Database.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.FwsAction", b =>
                {
                    b.Navigation("FwsLinks");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Conservation.NrcsPractice", b =>
                {
                    b.Navigation("FwsLinks");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Municipalities.Municipality", b =>
                {
                    b.Navigation("MunicipalitySpecies");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Sightings.UserSpecies", b =>
                {
                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("FaunaFinder.Database.Models.Species.Species", b =>
                {
                    b.Navigation("FwsLinks");

                    b.Navigation("Locations");

                    b.Navigation("MunicipalitySpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
