// <auto-generated />
using FaunaFinder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaunaFinder.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FaunaFinderDbContext))]
    partial class FaunaFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaunaFinder.Core.Entities.FwsAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FwsActions");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.FwsLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FwsActionId")
                        .HasColumnType("integer");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("NrcsPracticeId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FwsActionId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("NrcsPracticeId", "FwsActionId", "SpeciesId");

                    b.ToTable("FwsLinks");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GeoJsonId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GeoJsonId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.MunicipalitySpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("MunicipalityId", "SpeciesId")
                        .IsUnique();

                    b.ToTable("MunicipalitySpecies");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.NrcsPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NrcsPractices");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CommonName");

                    b.HasIndex("ScientificName");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.FwsLink", b =>
                {
                    b.HasOne("FaunaFinder.Core.Entities.FwsAction", "FwsAction")
                        .WithMany("FwsLinks")
                        .HasForeignKey("FwsActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaunaFinder.Core.Entities.NrcsPractice", "NrcsPractice")
                        .WithMany("FwsLinks")
                        .HasForeignKey("NrcsPracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaunaFinder.Core.Entities.Species", "Species")
                        .WithMany("FwsLinks")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FwsAction");

                    b.Navigation("NrcsPractice");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.MunicipalitySpecies", b =>
                {
                    b.HasOne("FaunaFinder.Core.Entities.Municipality", "Municipality")
                        .WithMany("MunicipalitySpecies")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaunaFinder.Core.Entities.Species", "Species")
                        .WithMany("MunicipalitySpecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipality");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.FwsAction", b =>
                {
                    b.Navigation("FwsLinks");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.Municipality", b =>
                {
                    b.Navigation("MunicipalitySpecies");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.NrcsPractice", b =>
                {
                    b.Navigation("FwsLinks");
                });

            modelBuilder.Entity("FaunaFinder.Core.Entities.Species", b =>
                {
                    b.Navigation("FwsLinks");

                    b.Navigation("MunicipalitySpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
